version = 8

[[source_groups]]
id = "9cb4e696-ff4d-4625-8f00-c81e41d8204f"
cpp_standard = "c++20"
header_search_paths = ""
name = "C++ Source Group"
pch_flags = ""
source_extensions = ""
source_paths = ""
status = "enabled"
type = "C++ Source Group"

[source_groups.cross_compilation]
target_options_enabled = "0"

[source_groups.cross_compilation.target]
abi = "unknown"
arch = "x86_64"
sys = "unknown"
vendor = "unknown"
