version = '8'

[[source_groups]]
id = '01d98a69-0204-4cfc-a6b7-894adb4b5de4'
name = 'C/C++ from Compilation Database'
status = 'enabled'
type = 'C/C++ from Compilation Database'

    [source_groups.build_file_path]
    compilation_db_path = '../../build/vcpkg-release/compile_commands.json'

    [source_groups.header_search_paths]
    header_search_path = [
        '../src/external/sqlite',
        '../../build/vcpkg-release/vcpkg_installed/x64-arm64-linux-windows-osx-static-md/include',
        '../../build/vcpkg-release/vcpkg_installed/x64-arm64-linux-windows-osx-static-md/include/Qt6',
        '../../build/vcpkg-release/vcpkg_installed/x64-arm64-linux-windows-osx-static-md/include/Qt6/QtCore',
        '../../build/vcpkg-release/vcpkg_installed/x64-arm64-linux-windows-osx-static-md/include/Qt6/QtWidgets',
        '../../build/vcpkg-release/vcpkg_installed/x64-arm64-linux-windows-osx-static-md/include/Qt6/QtGui',
        '../../build/vcpkg-release/vcpkg_installed/x64-arm64-linux-windows-osx-static-md/include/Qt6/QtSvg',
        '../../build/vcpkg-release/vcpkg_installed/x64-arm64-linux-windows-osx-static-md/include/Qt6/QtNetwork'
    ]

    [source_groups.indexed_header_paths]
    indexed_header_path = [ '..', '../../build/vcpkg-release' ]

    [source_groups.pch_flags]
    use_compiler_flags = '0'
