version = '8'

[[source_groups]]
id = '1666d109-acab-4e95-af66-c19a76ea75c4'
name = 'Rust Source Group'
status = 'enabled'
type = 'Rust Source Group'

    [source_groups.source_extensions]
    source_extension = '.rs'

    [source_groups.source_paths]
    source_path = './'
