description = 'Test Suites:\n\n [::\tmVIEW_TESTS\ts\tp]\n [::\tmGRAPH_TESTS\ts\tp]\n [::\tmCODE_TESTS\ts\tp]\n [::\tmHISTORY_TESTS\ts\tp]\n'
version = '8'

[[source_groups]]
cpp_standard = 'c++17'
id = '475571d1-b082-4fff-81c5-d099c19f957d'
name = 'C++ Source Group'
status = 'enabled'
type = 'C++ Source Group'

    [source_groups.cross_compilation]
    target_options_enabled = '0'

        [source_groups.cross_compilation.target]
        abi = 'unknown'
        arch = 'x86_64'
        sys = 'unknown'
        vendor = 'unknown'

    [source_groups.exclude_filters]
    exclude_filter = 'data/files/template.h'

    [source_groups.source_extensions]
    source_extension = [ '.cpp', '.cxx', '.cc' ]

    [source_groups.source_paths]
    source_path = 'data'
