// The row types are the object-API ("native") mirrors generated by
// `flatc --gen-object-api` (reference classes with pack/unpack). Kept under the
// `Owned*` names via typealiases so the collection code (StorageBuilder) and the
// tests are unchanged; the per-field serializer is replaced by pack (see
// context/DESIGN_STORAGE_CODEGEN.md). Convenience inits below preserve the old
// value-struct initializers so construction sites need no edits.

package typealias OwnedStorageNode = Sourcetrail_Ipc_StorageNodeT
package typealias OwnedStorageFile = Sourcetrail_Ipc_StorageFileT
package typealias OwnedStorageEdge = Sourcetrail_Ipc_StorageEdgeT
package typealias OwnedStorageSymbol = Sourcetrail_Ipc_StorageSymbolT
package typealias OwnedStorageComponentAccess = Sourcetrail_Ipc_StorageComponentAccessT
package typealias OwnedStorageSourceLocation = Sourcetrail_Ipc_StorageSourceLocationT
package typealias OwnedStorageLocalSymbol = Sourcetrail_Ipc_StorageLocalSymbolT
package typealias OwnedStorageOccurrence = Sourcetrail_Ipc_StorageOccurrenceT
package typealias OwnedStorageError = Sourcetrail_Ipc_StorageErrorT

extension Sourcetrail_Ipc_StorageNodeT {
	package convenience init(id: Int64, type: Int32, serializedName: String, modifiers: Int32 = 0) {
		self.init()
		self.id = id
		self.type = type
		self.serializedName = serializedName
		self.modifiers = modifiers
	}
}

extension Sourcetrail_Ipc_StorageFileT {
	package convenience init(
		id: Int64, filePath: String, languageIdentifier: String = "swift",
		indexed: Bool = true, complete: Bool
	) {
		self.init()
		self.id = id
		self.filePath = filePath
		self.languageIdentifier = languageIdentifier
		self.indexed = indexed
		self.complete = complete
	}
}

extension Sourcetrail_Ipc_StorageEdgeT {
	package convenience init(id: Int64, type: Int32, sourceNodeId: Int64, targetNodeId: Int64) {
		self.init()
		self.id = id
		self.type = type
		self.sourceNodeId = sourceNodeId
		self.targetNodeId = targetNodeId
	}
}

extension Sourcetrail_Ipc_StorageSymbolT {
	package convenience init(id: Int64, definitionKind: Int32) {
		self.init()
		self.id = id
		self.definitionKind = definitionKind
	}
}

extension Sourcetrail_Ipc_StorageComponentAccessT {
	package convenience init(nodeId: Int64, type: Int32) {
		self.init()
		self.nodeId = nodeId
		self.type = type
	}
}

extension Sourcetrail_Ipc_StorageSourceLocationT {
	package convenience init(
		id: Int64, fileNodeId: Int64, startLine: UInt32, startCol: UInt32,
		endLine: UInt32, endCol: UInt32, type: Int32
	) {
		self.init()
		self.id = id
		self.fileNodeId = fileNodeId
		self.startLine = startLine
		self.startCol = startCol
		self.endLine = endLine
		self.endCol = endCol
		self.type = type
	}
}

extension Sourcetrail_Ipc_StorageLocalSymbolT {
	package convenience init(id: Int64, name: String) {
		self.init()
		self.id = id
		self.name = name
	}
}

extension Sourcetrail_Ipc_StorageOccurrenceT {
	package convenience init(elementId: Int64, sourceLocationId: Int64) {
		self.init()
		self.elementId = elementId
		self.sourceLocationId = sourceLocationId
	}
}

extension Sourcetrail_Ipc_StorageErrorT {
	package convenience init(
		id: Int64, message: String, translationUnit: String, fatal: Bool, indexed: Bool = true
	) {
		self.init()
		self.id = id
		self.message = message
		self.translationUnit = translationUnit
		self.fatal = fatal
		self.indexed = indexed
	}
}

// Hand-written collection container: the generated row types live in
// non-optional arrays for ergonomic building; serialization maps them into the
// generated IntermediateStorageT (whose vectors are `[T?]`) and packs it.
package struct OwnedIntermediateStorage {
	package var nextId: Int64 = 1
	package var nodes: [OwnedStorageNode] = []
	package var files: [OwnedStorageFile] = []
	package var edges: [OwnedStorageEdge] = []
	package var symbols: [OwnedStorageSymbol] = []
	package var componentAccesses: [OwnedStorageComponentAccess] = []
	package var sourceLocations: [OwnedStorageSourceLocation] = []
	package var localSymbols: [OwnedStorageLocalSymbol] = []
	package var occurrences: [OwnedStorageOccurrence] = []
	package var errors: [OwnedStorageError] = []

	package init() {}

	package mutating func allocateId() -> Int64 {
		defer { nextId += 1 }
		return nextId
	}
}
