#pragma once

// clang-format off
// generated by: tools/sqlpp23/ddl2cpp/sqlpp23-ddl2cpp \
//     --path-to-ddl meta.sql --path-to-header MetaTable.h --namespace meta --assume-auto-id
// Regenerate from meta.sql when the schema changes. The `key` column survives
// because the vendored ddl2cpp carries the [reserved-word-column] fix.

#include <optional>

// The sqlpp23 DSL machinery (table_t/table_columns/type_traits) comes from `import sqlpp23.core` when the
// consuming TU imports it (SRCTRL_SQLPP23_MODULE); the SQLPP_CREATE_NAME_TAG macro can't cross an import,
// so create_name_tag.h is always #included textually.
#ifndef SRCTRL_SQLPP23_MODULE
#include <sqlpp23/core/basic/table.h>
#include <sqlpp23/core/basic/table_columns.h>
#endif
#include <sqlpp23/core/name/create_name_tag.h>
#ifndef SRCTRL_SQLPP23_MODULE
#include <sqlpp23/core/type_traits.h>
#endif

namespace meta {
  struct Meta_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    struct Key {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(key, key);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    struct Value {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(value, value);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(meta, meta);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               Key,
               Value>;
    using _required_insert_columns = sqlpp::detail::type_set<>;
  };
  using Meta = ::sqlpp::table_t<Meta_>;

} // namespace meta
