#pragma once

// clang-format off
// generated by: tools/sqlpp23/ddl2cpp/sqlpp23-ddl2cpp \
//     --path-to-ddl index.sql --path-to-header IndexTables.h --namespace idx --assume-auto-id
// Regenerate from index.sql when the schema changes (promoted from
// sqlpp23_poc/ in Phase 4).
//
// MANUAL CORRECTION [PK-is-FK]: --assume-auto-id marks every PK `id` as
// auto-increment (has_default=true, omittable). That is correct for `element`,
// `element_component` and `source_location` (real auto rowids), but WRONG for the
// tables whose `id` is a FOREIGN KEY to another table's id -- it must be supplied,
// not auto-assigned. Those ids are hand-set to required (has_default=false + added
// to _required_insert_columns). Re-apply after regenerating.
//   FK-primary-key tables (all corrected below):
//   edge, node, symbol, file, filecontent, local_symbol, error

#include <optional>

#include <sqlpp23/core/basic/table.h>
#include <sqlpp23/core/basic/table_columns.h>
#include <sqlpp23/core/name/create_name_tag.h>
#include <sqlpp23/core/type_traits.h>

namespace idx {
  struct Element_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(element, element);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id>;
    using _required_insert_columns = sqlpp::detail::type_set<>;
  };
  using Element = ::sqlpp::table_t<Element_>;

  struct ElementComponent_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    struct ElementId {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(element_id, elementId);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    struct Type {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(type, type);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    struct Data {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(data, data);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(element_component, elementComponent);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               ElementId,
               Type,
               Data>;
    using _required_insert_columns = sqlpp::detail::type_set<>;
  };
  using ElementComponent = ::sqlpp::table_t<ElementComponent_>;

  struct Edge_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;  // [PK-is-FK] id references element(id)
    };
    struct Type {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(type, type);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;
    };
    struct SourceNodeId {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(source_node_id, sourceNodeId);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;
    };
    struct TargetNodeId {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(target_node_id, targetNodeId);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(edge, edge);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               Type,
               SourceNodeId,
               TargetNodeId>;
    using _required_insert_columns = sqlpp::detail::type_set<  // [PK-is-FK] Id added
               sqlpp::column_t<sqlpp::table_t<Edge_>, Id>,
               sqlpp::column_t<sqlpp::table_t<Edge_>, Type>,
               sqlpp::column_t<sqlpp::table_t<Edge_>, SourceNodeId>,
               sqlpp::column_t<sqlpp::table_t<Edge_>, TargetNodeId>>;
  };
  using Edge = ::sqlpp::table_t<Edge_>;

  struct Node_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;  // [PK-is-FK] id references element(id)
    };
    struct Type {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(type, type);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;
    };
    struct SerializedName {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(serialized_name, serializedName);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    struct Modifiers {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(modifiers, modifiers);
      using data_type = ::sqlpp::integral;
      using has_default = std::true_type;  // DEFAULT 0 (NodeModifier bitmask)
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(node, node);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               Type,
               SerializedName,
               Modifiers>;
    using _required_insert_columns = sqlpp::detail::type_set<  // [PK-is-FK] Id added
               sqlpp::column_t<sqlpp::table_t<Node_>, Id>,
               sqlpp::column_t<sqlpp::table_t<Node_>, Type>>;
  };
  using Node = ::sqlpp::table_t<Node_>;

  struct Symbol_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;  // [PK-is-FK] id references node(id)
    };
    struct DefinitionKind {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(definition_kind, definitionKind);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(symbol, symbol);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               DefinitionKind>;
    using _required_insert_columns = sqlpp::detail::type_set<  // [PK-is-FK] Id added
               sqlpp::column_t<sqlpp::table_t<Symbol_>, Id>,
               sqlpp::column_t<sqlpp::table_t<Symbol_>, DefinitionKind>>;
  };
  using Symbol = ::sqlpp::table_t<Symbol_>;

  struct File_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;  // [PK-is-FK] id references node(id)
    };
    struct Path {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(path, path);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    struct Language {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(language, language);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    struct ModificationTime {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(modification_time, modificationTime);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    struct Indexed {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(indexed, indexed);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    struct Complete {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(complete, complete);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    struct LineCount {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(line_count, lineCount);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(file, file);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               Path,
               Language,
               ModificationTime,
               Indexed,
               Complete,
               LineCount>;
    using _required_insert_columns = sqlpp::detail::type_set<  // [PK-is-FK] Id added
               sqlpp::column_t<sqlpp::table_t<File_>, Id>>;
  };
  using File = ::sqlpp::table_t<File_>;

  struct Filecontent_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;  // [PK-is-FK] id references file(id)
    };
    struct Content {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(content, content);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(filecontent, filecontent);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               Content>;
    using _required_insert_columns = sqlpp::detail::type_set<  // [PK-is-FK] Id added
               sqlpp::column_t<sqlpp::table_t<Filecontent_>, Id>>;
  };
  using Filecontent = ::sqlpp::table_t<Filecontent_>;

  struct FileCommandHash_ {
    struct Path {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(path, path);
      using data_type = ::sqlpp::text;
      using has_default = std::false_type;
    };
    struct Hash {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(hash, hash);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(file_command_hash, fileCommandHash);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Path,
               Hash>;
    using _required_insert_columns = sqlpp::detail::type_set<
               sqlpp::column_t<sqlpp::table_t<FileCommandHash_>, Path>>;
  };
  using FileCommandHash = ::sqlpp::table_t<FileCommandHash_>;

  struct LocalSymbol_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;  // [PK-is-FK] id references element(id)
    };
    struct Name {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(name, name);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(local_symbol, localSymbol);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               Name>;
    using _required_insert_columns = sqlpp::detail::type_set<  // [PK-is-FK] Id added
               sqlpp::column_t<sqlpp::table_t<LocalSymbol_>, Id>>;
  };
  using LocalSymbol = ::sqlpp::table_t<LocalSymbol_>;

  struct SourceLocation_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::integral;
      using has_default = std::true_type;
    };
    struct FileNodeId {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(file_node_id, fileNodeId);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    struct StartLine {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(start_line, startLine);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    struct StartColumn {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(start_column, startColumn);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    struct EndLine {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(end_line, endLine);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    struct EndColumn {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(end_column, endColumn);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    struct Type {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(type, type);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(source_location, sourceLocation);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               FileNodeId,
               StartLine,
               StartColumn,
               EndLine,
               EndColumn,
               Type>;
    using _required_insert_columns = sqlpp::detail::type_set<>;
  };
  using SourceLocation = ::sqlpp::table_t<SourceLocation_>;

  struct Occurrence_ {
    struct ElementId {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(element_id, elementId);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;
    };
    struct SourceLocationId {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(source_location_id, sourceLocationId);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(occurrence, occurrence);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               ElementId,
               SourceLocationId>;
    using _required_insert_columns = sqlpp::detail::type_set<
               sqlpp::column_t<sqlpp::table_t<Occurrence_>, ElementId>,
               sqlpp::column_t<sqlpp::table_t<Occurrence_>, SourceLocationId>>;
  };
  using Occurrence = ::sqlpp::table_t<Occurrence_>;

  struct ComponentAccess_ {
    struct NodeId {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(node_id, nodeId);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;
    };
    struct Type {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(type, type);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(component_access, componentAccess);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               NodeId,
               Type>;
    using _required_insert_columns = sqlpp::detail::type_set<
               sqlpp::column_t<sqlpp::table_t<ComponentAccess_>, NodeId>,
               sqlpp::column_t<sqlpp::table_t<ComponentAccess_>, Type>>;
  };
  using ComponentAccess = ::sqlpp::table_t<ComponentAccess_>;

  struct Error_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;  // [PK-is-FK] id references element(id)
    };
    struct Message {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(message, message);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    struct Fatal {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(fatal, fatal);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;
    };
    struct Indexed {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(indexed, indexed);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;
    };
    struct TranslationUnit {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(translation_unit, translationUnit);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(error, error);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               Message,
               Fatal,
               Indexed,
               TranslationUnit>;
    using _required_insert_columns = sqlpp::detail::type_set<  // [PK-is-FK] Id added
               sqlpp::column_t<sqlpp::table_t<Error_>, Id>,
               sqlpp::column_t<sqlpp::table_t<Error_>, Fatal>,
               sqlpp::column_t<sqlpp::table_t<Error_>, Indexed>>;
  };
  using Error = ::sqlpp::table_t<Error_>;

} // namespace idx
