#pragma once

// clang-format off
// generated by sqlpp23-ddl2cpp --path-to-ddl bookmark.sql --path-to-header BookmarkTables.h --namespace bm --assume-auto-id
//
// MANUAL CORRECTION (see [PK-is-FK] below): --assume-auto-id marks every PK `id`
// as auto-increment (has_default=true, omittable). That is correct for
// bookmark_category / bookmark, but WRONG for bookmarked_node / bookmarked_edge,
// whose `id` is a FOREIGN KEY to bookmarked_element(id) -- it must equal the
// element rowid, not a fresh auto value. Those two ids are hand-set back to
// required. ddl2cpp cannot infer this; re-apply after regenerating.

#include <optional>

#include <sqlpp23/core/basic/table.h>
#include <sqlpp23/core/basic/table_columns.h>
#include <sqlpp23/core/name/create_name_tag.h>
#include <sqlpp23/core/type_traits.h>

namespace bm {
  struct BookmarkCategory_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::integral;
      using has_default = std::true_type;
    };
    struct Name {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(name, name);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(bookmark_category, bookmarkCategory);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               Name>;
    using _required_insert_columns = sqlpp::detail::type_set<>;
  };
  using BookmarkCategory = ::sqlpp::table_t<BookmarkCategory_>;

  struct Bookmark_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::integral;
      using has_default = std::true_type;
    };
    struct Name {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(name, name);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    struct Comment {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(comment, comment);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    struct Timestamp {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(timestamp, timestamp);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    struct CategoryId {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(category_id, categoryId);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(bookmark, bookmark);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               Name,
               Comment,
               Timestamp,
               CategoryId>;
    using _required_insert_columns = sqlpp::detail::type_set<>;
  };
  using Bookmark = ::sqlpp::table_t<Bookmark_>;

  struct BookmarkedElement_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::integral;
      using has_default = std::true_type;
    };
    struct BookmarkId {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(bookmark_id, bookmarkId);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(bookmarked_element, bookmarkedElement);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               BookmarkId>;
    using _required_insert_columns = sqlpp::detail::type_set<
               sqlpp::column_t<sqlpp::table_t<BookmarkedElement_>, BookmarkId>>;
  };
  using BookmarkedElement = ::sqlpp::table_t<BookmarkedElement_>;

  struct BookmarkedNode_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;  // [PK-is-FK] id references bookmarked_element(id)
    };
    struct SerializedNodeName {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(serialized_node_name, serializedNodeName);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(bookmarked_node, bookmarkedNode);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               SerializedNodeName>;
    using _required_insert_columns = sqlpp::detail::type_set<  // [PK-is-FK]
               sqlpp::column_t<sqlpp::table_t<BookmarkedNode_>, Id>>;
  };
  using BookmarkedNode = ::sqlpp::table_t<BookmarkedNode_>;

  struct BookmarkedEdge_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;  // [PK-is-FK] id references bookmarked_element(id)
    };
    struct SerializedSourceNodeName {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(serialized_source_node_name, serializedSourceNodeName);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    struct SerializedTargetNodeName {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(serialized_target_node_name, serializedTargetNodeName);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    struct EdgeType {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(edge_type, edgeType);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    struct SourceNodeActive {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(source_node_active, sourceNodeActive);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(bookmarked_edge, bookmarkedEdge);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               SerializedSourceNodeName,
               SerializedTargetNodeName,
               EdgeType,
               SourceNodeActive>;
    using _required_insert_columns = sqlpp::detail::type_set<  // [PK-is-FK]
               sqlpp::column_t<sqlpp::table_t<BookmarkedEdge_>, Id>>;
  };
  using BookmarkedEdge = ::sqlpp::table_t<BookmarkedEdge_>;

} // namespace bm
