#pragma once

// clang-format off
// generated by sqlpp23-ddl2cpp --path-to-ddl meta.sql --path-to-header MetaTable.h --namespace meta --assume-auto-id
//
// MANUAL CORRECTION [reserved-word]: ddl2cpp SILENTLY DROPPED the `key` column.
// `key` is a SQL reserved word (PRIMARY KEY / FOREIGN KEY), so the generator's
// grammar mis-parses a column literally named `key` and emits a Meta_ with only
// Id and Value -- losing the very column the meta table is keyed on. The Key
// struct below was added by hand. Re-check after regenerating; consider renaming
// the physical column if the schema ever gets revised.
//
// NOTE: tools/sqlpp23/ddl2cpp now carries a fix for this ([reserved-word-column]),
// so a fresh generation keeps `key`. This header retains the note for provenance.

#include <optional>

#include <sqlpp23/core/basic/table.h>
#include <sqlpp23/core/basic/table_columns.h>
#include <sqlpp23/core/name/create_name_tag.h>
#include <sqlpp23/core/type_traits.h>

namespace meta {
  struct Meta_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    struct Key {  // [reserved-word] added by hand; ddl2cpp dropped this column
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(key, key);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    struct Value {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(value, value);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(meta, meta);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               Key,
               Value>;
    using _required_insert_columns = sqlpp::detail::type_set<>;
  };
  using Meta = ::sqlpp::table_t<Meta_>;

} // namespace meta
