// Generates Rust FlatBuffers bindings from the *same* agent-control schemas the
// C++ side uses (src/lib/component/controller/agent_control/schemas/*.fbs), so the
// bridge and the app share one source of truth for the wire contracts. Mirrors the
// C++ `flatc --cpp` generation in src/lib/CMakeLists.txt.
//
// Each root schema is generated as a self-contained `--gen-onefile` module (which
// inlines the included agent_common.fbs), so there are no cross-file module-path
// headaches; the duplicated shared types live in separate Rust modules and never
// need to be the same type (the bridge projects everything to serde_json anyway).
//
// flatc is located via $FLATC, else the project's vcpkg copy, else PATH.

use std::path::{Path, PathBuf};
use std::process::Command;

fn find_flatc(manifest: &Path) -> String {
    if let Ok(f) = std::env::var("FLATC") {
        return f;
    }
    // Project vcpkg install (…/.build/<preset>/vcpkg_installed/<triplet>/tools/flatbuffers/flatc).
    let root = manifest.join("../..");
    if let Ok(entries) = glob_flatc(&root.join(".build")) {
        if let Some(p) = entries {
            return p.to_string_lossy().into_owned();
        }
    }
    "flatc".to_string()
}

fn glob_flatc(build_dir: &Path) -> std::io::Result<Option<PathBuf>> {
    if !build_dir.is_dir() {
        return Ok(None);
    }
    for preset in std::fs::read_dir(build_dir)? {
        let candidate = preset?
            .path()
            .join("vcpkg_installed");
        if let Ok(triplets) = std::fs::read_dir(&candidate) {
            for t in triplets.flatten() {
                let f = t.path().join("tools/flatbuffers/flatc");
                if f.is_file() {
                    return Ok(Some(f));
                }
            }
        }
    }
    Ok(None)
}

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let schema_dir = manifest.join("../lib/component/controller/agent_control/schemas");
    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let flatc = find_flatc(&manifest);

    // flatc's Rust codegen does not inline includes, and its multi-file output
    // has namespace collisions for same-namespace includes (every file redeclares
    // `pub mod sourcetrail`, shadowing the shared types). So we merge all schemas
    // into one self-contained schema — single namespace, no includes, no
    // root_type — and generate a single clean module. Decoding uses the generic
    // `flatbuffers::root::<T>` (no per-root `root_as_*` helpers needed).
    let schemas = [
        "agent_common.fbs", // shared types first (defined before use)
        "agent_command.fbs",
        "agent_event.fbs",
        "agent_state.fbs",
        "agent_frame.fbs",
        "agent_snapshot.fbs",
    ];

    let mut merged = String::from("// @generated by build.rs from the agent-control schemas\nnamespace Sourcetrail.Agent;\n\n");
    for fbs in schemas {
        let path = schema_dir.join(fbs);
        println!("cargo:rerun-if-changed={}", path.display());
        let text = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        for line in text.lines() {
            let t = line.trim_start();
            if t.starts_with("include ") || t.starts_with("namespace ") || t.starts_with("root_type ") {
                continue;
            }
            merged.push_str(line);
            merged.push('\n');
        }
    }
    println!("cargo:rerun-if-env-changed=FLATC");

    let merged_fbs = out.join("agent_bridge.fbs");
    std::fs::write(&merged_fbs, &merged).unwrap();

    let status = Command::new(&flatc)
        .args(["--rust", "--gen-onefile", "-o"])
        .arg(&out)
        .arg(&merged_fbs)
        .status()
        .unwrap_or_else(|e| panic!("failed to run flatc ({flatc}): {e}"));
    assert!(status.success(), "flatc failed");

    // Discover the generated .rs (name/suffix varies by flatc version).
    let generated = std::fs::read_dir(&out)
        .unwrap()
        .filter_map(Result::ok)
        .map(|e| e.path())
        .find(|p| {
            p.file_name()
                .and_then(|n| n.to_str())
                .is_some_and(|n| n.starts_with("agent_bridge") && n.ends_with(".rs"))
        })
        .expect("flatc produced no agent_bridge*.rs");

    std::fs::write(
        out.join("schema_gen.rs"),
        format!(
            "#[allow(dead_code, unused_imports, clippy::all)]\npub mod schema {{ include!(r\"{}\"); }}\n",
            generated.display()
        ),
    )
    .unwrap();
}
